import Vue from 'vue'
import {
    Upload,
    MessageBox,
    Button,
    Form,
    FormItem,
    Input,
    Message,
    Container,
    Header,
    Aside,
    Main,
    Menu,
    Submenu,
    MenuItem,
    Breadcrumb,
    BreadcrumbItem,
    Card,
    Row,
    Col,
    Table,
    TableColumn,
    Switch,
    Tooltip,
    Pagination,
    Dialog,
    Tag,
    Tree,
    Select,
    Option,
    Cascader,
    Alert,
    Tabs,
    TabPane,
    Steps,
    Step,
    Checkbox,
    CheckboxGroup
} from 'element-ui'

Vue.use(Button)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Form)
    .use(FormItem)
    .use(Input)
    .use(Container)
    .use(Header)
    .use(Aside)
    .use(Main)
    .use(Menu)
    .use(Submenu)
    .use(MenuItem)
    .use(Breadcrumb)
    .use(BreadcrumbItem)
    .use(Card)
    .use(Row)
    .use(Col)
    .use(Table)
    .use(TableColumn)
    .use(Switch)
    .use(Tooltip)
    .use(Pagination)
    .use(Dialog)
    .use(Tag)
    .use(Select)
    .use(Tree)
    .use(Option)
    .use(Cascader)
    .use(Alert)
    .use(Tabs)
    .use(TabPane)
    .use(Steps)
    .use(Step)
    .use(Upload)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm